### PR TITLE
Add wrap files for mocklibc-1.0

### PR DESCRIPTION
**Pull request by inigomartinez**

### CODE REVIEW

**Comment by sarum9in** [comment]
It failed for me on the test step. Could you please take a look if this is expected?

```
$ mesonwrap review mocklibc --pull_request=1 --allow_other_files
Inspecting project mocklibc, branch 1.0.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☑
Has upstream.wrap: ☑
Non-buildsystem files found:
  bin/mocklibc.in
  bin/mocklibc-test.in
Repo contains only buildsystem files: ☒
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
upstream.wrap has source_url with version substring: ☑
Download URL works: ☑
Hash matches: ☑
upstream.wrap directory 'mocklibc-1.0' exists: ☑
Patch merges with source: ☑
The Meson build system
Version: 0.49.0
Source dir: /tmp/tmpv85ls0vc/src/mocklibc-1.0
Build dir: /tmp/tmpv85ls0vc/bin
Build type: native build
Project name: mocklibc
Project version: 1.0
Native C compiler: cc (gcc 8.2.1 "cc (GCC) 8.2.1 20181127")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring mocklibc using configuration
Program bash found: YES (/usr/bin/bash)
Configuring mocklibc-test using configuration
Build targets in project: 2
Found ninja-1.8.2 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmpv85ls0vc/bin'
[5/9] Compiling C object 'src/25a6634@@mocklibc-debug-netgroup@exe/netgroup-debug.c.o'.
../src/mocklibc-1.0/src/netgroup-debug.c: In function ‘netgroup_debug_print_entry’:
../src/mocklibc-1.0/src/netgroup-debug.c:25:3: warning: implicit declaration of function ‘print_indent’ [-Wimplicit-function-declaration]
   print_indent(stream, indent);
   ^~~~~~~~~~~~
[8/9] Running all tests.
1/1 mocklibc-test                           FAIL     0.49 s (exit status 1)

Ok:                    0
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0


The output from the failed tests:

1/1 mocklibc-test                           FAIL     0.49 s (exit status 1)

--- command ---
/usr/bin/bash /tmp/tmpv85ls0vc/bin/bin/mocklibc-test
--- stdout ---
Test Failed:

Test Failed:

Test Failed:

Test Failed:

Test Failed:

Test Failed:

Test Failed:

Failed 7 of 23 tests.
--- stderr ---
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr foo -u john
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr bar -u jane
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr baz -u john
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr baz -u jane
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr all -u john
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr all -u jane
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
assert true: innetgr all -u henry
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
/tmp/tmpv85ls0vc/bin/bin/mocklibc: line 30: exec: innetgr: not found
-------

Full log written to /tmp/tmpv85ls0vc/bin/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
ninja test: ☒
```

**Comment by inigomartinez** [comment]
Yes, it might fail because it doesn't check whether `innetgr` exists on the system. I haven't done any improvement because autotools also doesn't do any check about this issue.

**Comment by sarum9in** [comment]
I can't find what package contains `innetgr`. What project does it come from? I use Arch Linux and it is not included in standard distribution, though man-page exists for a function.

**Comment by inigomartinez** [comment]
In my local system, Debian, it is included in the [`ng-utils` package](https://packages.debian.org/sid/ng-utils).

**Comment by sarum9in** [comment]
https://tracker.debian.org/pkg/ng-utils is a pretty old package
it works just fine on ArchLinux though, but I need to install it in order to test the wrap.
I don't like that this wrap is usable only on Debian. I wonder if it would be possible to make it distro-agnostic. If I am wrong and ArchLinux is in the minority where innetgr is not shipped by default I can try to fix it.

For now next step for me is to actually install innetgr and test the wrap.
For @inigomartinez: what do you think about the portability?

**Comment by inigomartinez** [comment]
I'm not sure if `innetgr` is only limited to Debian. As you said, it's a quite old package and probably it has been removed from almost all the known distros. Taking this in consideration, I would choose between the following two options:

1. Add an option to disable tests, and/or make it conditionally dependent on the existence of the binary in the system.
2. Split the `mocklibc-test` script in three smaller tests and, again, add an option for each tests so they can be disabled, and/or make them conditionally dependent on the existence of the necessary binaries in the system.

**Comment by sarum9in** [comment]
I think autodetection of `innetgr` and disabling of certain tests would make sense in this case.
Just printing a warning that tests were skipped is probably enough for this wrap. We can reiterate on this in the future.

I would do it like that (modulo actually including tests instead of printing the message)

```meson
project('testing')

if find_program('innetgr', required: false).found()
  message('found')
else
  message('not found')
endif
```

**Comment by inigomartinez** [comment]
I have changed the commit so the `mocklibc-test` creation and testing is conditionally dependent on `innetgr` (I'm also considering that `id` will always be available).

**Comment by sarum9in** [comment]
Okay, it builds now. Could you please also define `mocklibc_dep` as other wraps do?
[Example](https://github.com/mesonbuild/jansson/blob/2.11/meson.build#L97).

**Comment by inigomartinez** [comment]
> Okay, it builds now. Could you please also define `mocklibc_dep` as other wraps do?
> [Example](https://github.com/mesonbuild/jansson/blob/2.11/meson.build#L97).

Done. I haven't done it before because it's not an usual library. It only exposes the library itself that must be placed before the real system `libc` (something that is done by setting the `LD_PRELOAD` environment variable or just using the provided `mocklibc`).

**Comment by sarum9in** [comment]
Hmm, I see, I didn't think about it. I will add this comment to the build file.

**Pull request merged**
